### ISSUE TITLE
Can't comment out text with keyboard shortcut

### ISSUE THREAD

**Issue by Maidomax** [omissis/sublime-behat-syntax#12]
When I press `<Ctrl>+</>` I expect the selected text to be commented out as usual, but nothing happens. It's a real pain to need to comment out lines one by one.

**Comment by omissis** [comment]
@Maidomax do you still experience this issue? on mac it looks fine.

**Comment by omissis** [comment]
@Maidomax any news on this?

**Comment by Maidomax** [comment]
@omissis Holy, this is an old issue. I created this while working in the old company. I no longer use Sublime Text, I went over to PhpStorm, and I just use phpunit for testing. Don't know if I could remember how to set up everything to test this again.

**Comment by omissis** [comment]
@Maidomax ok thanks for the answer, I'll look into that should anyone else report it.
