### ISSUE TITLE
Step keyword highlighting not working in Subl3

### ISSUE THREAD

**Issue by GregKaleka** [omissis/sublime-behat-syntax#17]
I'm using beat in sublime text 3, and step keywords (Given, And, Then, etc) are not being highlighted.

Possibly due to my theme? Using Seti.sublime-theme with Facebook.tmTheme coloring.

<img width="397" alt="screen shot 2015-08-16 at 12 43 53 pm" src="https://cloud.githubusercontent.com/assets/11154227/9295025/83c11f34-4414-11e5-9490-ee55a2628548.png">

**Comment by arcturial** [comment]
Hey, yeah it looks like the theme. I will play around and see if I can get it to work with that theme.

**Comment by arcturial** [comment]
The author of the repository will attend to the PR as soon as possible. In the interim, you can try the version over at https://github.com/arcturial/sublime-behat-syntax which has the latest PR (until I can get it merged).

**Comment by GregKaleka** [comment]
Thanks arcturial! I'll give it a try this evening.

**Comment by omissis** [comment]
Hi, back from vacations today :) Hey @GregKaleka, did you try the fix? does it work? I will check it soon on my theme, too.

**Comment by arcturial** [comment]
@omissis you find any irregularities while testing on your theme?

**Comment by omissis** [comment]
@arcturial it works fine, I will be merging it.

**Comment by omissis** [comment]
Solved by PR 18: https://github.com/omissis/sublime-behat-syntax/pull/18
