### ISSUE TITLE
Keep getting error loading syntax file message

### ISSUE THREAD

**Issue by klop86** [omissis/sublime-behat-syntax#19]
![cloning_a_repository_-_user_documentation](https://cloud.githubusercontent.com/assets/2923359/13327481/fa6e98fe-dbe1-11e5-97fc-05efa71a1fa5.png)

See attached file. This happens when I select Behat from the list. After I press OK on the errors Behat disappears from the list of available languages.

**Comment by omissis** [comment]
Interesting. What version of sublime are you using?

**Comment by klop86** [comment]
Hi there.

I am using 2.0.2 build 2221 and El Capitan Version 10.11.3. See attached.

**Comment by omissis** [comment]
Ah, Sublime 2. I'm afraid this has only be tested on Sublime 3 in the last years, so I can't guarantee this will work or receive support in that I am not interested in supporting it. I should remove it from the package description.

**Comment by klop86** [comment]
Thank you! I installed v3 and all is working as advertised now.
