### ISSUE TITLE
Error Loading Syntax File

### ISSUE THREAD

**Issue by zweishar** [omissis/sublime-behat-syntax#20]
Getting this error message when trying to add sublime-behat-syntax to Sublime Text 2 (Version 2.0.2 Build 2221)

Steps to reproduce:
- Clone  repo to Sublime Text 2 Packages folder
- Open Sublime Text

Sublime text actually deletes this repo from its packages folder after experiencing this error. I'm guessing this is normal behavior when experiencing such an error, but I don't have enough experience with sublime to be sure.

I upgraded to Sublime Text 3 and had no problems installing.

<img width="324" alt="behat-sublime-error" src="https://cloud.githubusercontent.com/assets/8590743/21545577/c42ac210-cda6-11e6-8694-f6822841c4ff.png">

**Comment by omissis** [comment]
Hey @zweishar thanks for the report but Sublime Text 2 isn't supported any longer.
