### ISSUE TITLE
"fill in the following:" table syntax highlighting broken

### ISSUE THREAD

**Issue by g105b** [omissis/sublime-behat-syntax#21]
After a table node is defined, the syntax highlighting continues onto subsequent lines.

![image](https://cloud.githubusercontent.com/assets/358014/23020591/b03063c2-f43f-11e6-9ecd-f582d6a339f4.png)

**Comment by omissis** [comment]
hey @g105b thanks for the report, I'll look into it as soon as I'll find some time :)

**Comment by g105b** [comment]
I hope you're doing well. I haven't used Sublime for a long time now, so I'm closing this issue (going through old issues to tidy things up!)
